name: google_charts
version: 0.2.1
author: Robert Hartung <robert.w.hartung@gmail.com>
description: Google Charts API Wrapper Classes.
homepage: https://github.com/roberthartung/google_charts
environment:
    sdk: '>=2.1.0 <3.0.0'
dependencies:    
  reflectable: any
dev_dependencies:
  html: any
  http: any
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0


